"""
AI Marketing Content Engine — Master Content Schemas

Pydantic v2 validation models for Master Content output and API response.
"""

import uuid
from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, ConfigDict, Field

from app.schemas.strategy import CallToAction


class MasterContentOutput(BaseModel):
    """Structured platform-neutral Master Content generated by MasterContentAgent."""

    title: str = Field(
        ...,
        min_length=3,
        description="Master headline or theme title for the content pillar",
        examples=["Eliminating Jobsite Delays with Autonomous Safety Inspection AI"],
    )
    core_idea: str = Field(
        ...,
        min_length=10,
        description="Central core concept unifying the campaign message",
    )
    problem: str = Field(
        ...,
        min_length=10,
        description="Detailed breakdown of the customer problem and status quo pain points",
    )
    solution: str = Field(
        ...,
        min_length=10,
        description="Clear positioning of how the product/service solves the problem",
    )
    business_value: List[str] = Field(
        ...,
        min_length=2,
        description="Concrete financial, operational, or strategic value drivers",
    )
    target_personas: List[str] = Field(
        ...,
        min_length=1,
        description="Target personas addressed by this master content",
    )
    key_message: str = Field(
        ...,
        min_length=10,
        description="Single overarching key message statement",
    )
    cta: CallToAction = Field(
        ...,
        description="Primary and secondary call-to-actions",
    )

    model_config = ConfigDict(extra="ignore")


class MasterContentResponse(BaseModel):
    """API Response model for a master content entity."""

    id: uuid.UUID
    campaign_id: uuid.UUID
    content: MasterContentOutput
    status: str
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)
