"""
AI Marketing Content Engine — Strategy Schemas

Pydantic v2 validation models for Marketing Strategy output and API response.
"""

import uuid
from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, ConfigDict, Field


class CallToAction(BaseModel):
    """Primary and secondary call-to-action objects."""

    primary: str = Field(
        ...,
        description="Main direct call-to-action",
        examples=["Claim your free AI jobsite assessment"],
    )
    secondary: str = Field(
        default="Learn how AI is transforming construction safety",
        description="Softer engagement or educational call-to-action",
    )


class StrategyOutput(BaseModel):
    """Structured strategy generated by the StrategyAgent."""

    audience_insights: List[str] = Field(
        ...,
        min_length=2,
        description="Deep psychological and operational insights into target personas",
    )
    content_pillars: List[str] = Field(
        ...,
        min_length=2,
        description="Core strategic content themes (e.g., Risk Mitigation, Cost Efficiency)",
    )
    key_messages: List[str] = Field(
        ...,
        min_length=2,
        description="Essential value proposition messages to communicate across content",
    )
    topics: List[str] = Field(
        ...,
        min_length=3,
        description="Specific content topics derived from campaign pain points and pillars",
    )
    content_angles: List[str] = Field(
        ...,
        min_length=2,
        description="Unique narrative or positioning angles (e.g., Myth-busting, Data-driven ROI)",
    )
    cta: CallToAction = Field(
        ...,
        description="Primary and secondary call-to-actions",
    )

    model_config = ConfigDict(extra="ignore")


class StrategyResponse(BaseModel):
    """API Response model for a marketing strategy entity."""

    id: uuid.UUID
    campaign_id: uuid.UUID
    content: StrategyOutput
    status: str
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)
